name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Flet CLI
        run: |
          pip install "flet[all]"

      - name: Build APK
        run: |
          yes | flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Flow-APK
          path: build/apk/*.apk
